# Generated by Django 3.2.2 on 2021-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
