# Generated by Django 3.2.2 on 2021-05-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0003_pages_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
