# Generated by Django 3.2.2 on 2021-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_rename_pages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='shortDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
