# Generated by Django 3.2.2 on 2021-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0007_remove_page_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
