# Generated by Django 3.2.2 on 2021-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0009_page_sda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sda',
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
