# Generated by Django 3.2.2 on 2021-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0010_auto_20210701_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='PdfFile/'),
        ),
    ]
