# Generated by Django 4.1.7 on 2023-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0011_auto_20210701_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Каруселька', 'verbose_name_plural': 'Каруселька'},
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='PdfFile/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='PageImages/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='shortDescription',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='SlideImages/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='linkTo',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Под описание'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
