# Generated by Django 3.1.6 on 2021-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщений'},
        ),
        migrations.AddField(
            model_name='mail',
            name='content',
            field=models.TextField(default=1, verbose_name='content'),
            preserve_default=False,
        ),
    ]
