# Generated by Django 3.1.7 on 2021-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210216_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='content',
        ),
        migrations.AddField(
            model_name='mail',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
