# Generated by Django 4.0.4 on 2022-04-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20210326_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='TypeSeminar/')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='typeSeminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.typeseminar'),
        ),
    ]
