# Generated by Django 4.0.4 on 2022-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_typeseminar_mail_typeseminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
