# Generated by Django 4.1.7 on 2023-02-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_mail_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeseminar',
            options={'verbose_name': 'Тип семинара', 'verbose_name_plural': 'Типы семинара'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='typeSeminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.typeseminar', verbose_name='Тип семинара'),
        ),
    ]
